name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Show project structure
      shell: cmd
      run: |
        echo "=== Current Directory ==="
        cd
        echo "=== Project Structure ==="
        dir /S

    - name: Create lib directory
      shell: cmd
      run: |
        if not exist lib mkdir lib
        echo "=== Created lib directory ==="
        dir

    - name: Download SQLite JDBC
      shell: cmd
      run: |
        curl -L -o "lib\sqlite-jdbc-3.49.1.0.jar" "https://github.com/xerial/sqlite-jdbc/releases/download/3.49.1.0/sqlite-jdbc-3.49.1.0.jar"
        echo "=== Downloaded SQLite JDBC ==="
        dir lib
