name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Create directories
      run: |
        mkdir -p lib bin

    - name: Download dependencies
      run: |
        curl -L -o "lib/sqlite-jdbc-3.49.1.0.jar" "https://github.com/xerial/sqlite-jdbc/releases/download/3.49.1.0/sqlite-jdbc-3.49.1.0.jar"
        curl -L -o "lib/junit-4.13.2.jar" "https://repo1.maven.org/maven2/junit/junit/4.13.2/junit-4.13.2.jar"
        curl -L -o "lib/hamcrest-core-1.3.jar" "https://repo1.maven.org/maven2/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar"

    - name: List project structure
      run: |
        echo "Project structure:"
        find .
        echo "Content of src directory:"
        find src -type f

    - name: Build project
      run: |
        echo "Building project..."
        find src/main -name "*.java" | xargs javac -cp "lib/*" -d bin
        if [ $? -ne 0 ]; then
          echo "Build failed"
          exit 1
        fi

    - name: List compiled files
      run: |
        echo "Content of bin directory:"
        find bin -type f
        echo "Content of lib directory:"
        find lib -type f

    - name: Create artifact
      run: |
        jar cvf MissieMoustass.jar -C bin .

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: MissieMoustass
        path: MissieMoustass.jar
        if-no-files-found: error
