name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        # Suppression de la ligne cache: 'maven' qui causait l'erreur

    - name: Create directories
      shell: cmd
      run: |
        if not exist lib mkdir lib
        if not exist bin mkdir bin

    - name: Download dependencies
      shell: cmd
      run: |
        curl -L -o "lib\sqlite-jdbc-3.49.1.0.jar" "https://github.com/xerial/sqlite-jdbc/releases/download/3.49.1.0/sqlite-jdbc-3.49.1.0.jar"
        curl -L -o "lib\junit-4.13.2.jar" "https://repo1.maven.org/maven2/junit/junit/4.13.2/junit-4.13.2.jar"
        curl -L -o "lib\hamcrest-core-1.3.jar" "https://repo1.maven.org/maven2/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar"

    - name: List project structure
      shell: cmd
      run: |
        echo "Project structure:"
        dir /s /b
        echo "Content of src directory:"
        dir src /s /b

    - name: Build project
      shell: cmd
      run: |
        echo "Building project..."
        javac -cp "lib\*" -d bin src\main\*.java
        if errorlevel 1 (
          echo "Build failed"
          exit /b 1
        )

    - name: List compiled files
      shell: cmd
      run: |
        echo "Content of bin directory:"
        dir bin /s /b
        echo "Content of lib directory:"
        dir lib /s /b

    - name: Create artifact
      shell: cmd
      run: |
        jar cvf MissieMoustass.jar -C bin .

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: MissieMoustass
        path: MissieMoustass.jar
        if-no-files-found: error
